language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - mv conf.py.dist conf.py
  - echo LOG_ADDR = ('localhost', 514) >> conf.py

# command to run tests
script:
  - make tests
  - flake8 request_handler.py
  - flake8 tests.py
